sysAdmin: superAdmin
log:
  freq: hour
  useUTC: false
eastWealth:
  user:
    username: 1
    password: 1
  mysql:
    database: eastwealthcrawler
    host: 127.0.0.1
    port: 3306
    user: root
    password: 778699